import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/hero/Hero";
import Product from "@/components/products/Product";
import Why from "@/components/why/Why";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Moxieswap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-max w-full space-y-20">
        <Hero />
        <Product />
        <Why />
      </div>
    </>
  );
}
